### ISSUE TITLE
bgr.com blocked - some tech-related publication

### ISSUE THREAD

**Issue by thulle** [outapzaza/blocklist#2]
Tried reading https://bgr.com/2019/01/07/he-jiankui-armed-guard-punishment/ and was blocked by four entries (prefixed by line number):

1442:0.0.0.0 bgr.com
16954:0.0.0.0 bgr.com
35729:0.0.0.0 bgr.com
51608:0.0.0.0 bgr.com

**Comment by Tapao-NonSen** [comment]
Thank you for reporting. Now, I've solved the problem.

**Comment by thulle** [comment]
Unfortunately you removed one of the entries, three are still remaining.
