### ISSUE TITLE
multiple duplicate entries

### ISSUE THREAD

**Issue by thulle** [outapzaza/blocklist#3]
While searching for the blocking entry in #2 i found duplicates.
Runing the following command to prefix them with number of times they appear, the most frequent duplicate appears 36 times:
$ sort -n fingerprintblock.txt |uniq -c|sort -nr|head -n 10
     36 0.0.0.0 bankvarzesh.com
     28 0.0.0.0 yaspsd.ir
     28 0.0.0.0 vaghayedaily.ir
     24 0.0.0.0 rootech.ir
     24 0.0.0.0 khabarduni.ir
     20 0.0.0.0 iruni.ir
     20 0.0.0.0 6blog.ir
     16 0.0.0.0 rmsft.rozblog.com
     16 0.0.0.0 hoosheparsi.ir
     15 0.0.0.0 hahasforhoohas.com

**Comment by Tapao-NonSen** [comment]
Thank you for reporting. Now, I've solved the problem.

**Comment by thulle** [comment]
Those were just the top ones, you still have many remaining.. half the list is just duplicates. I can make a pull request..
